CONFIGURE = {
    "HOST": "0.0.0.0",
    "PORT": 12345,

    "GENERATE_MAX_X": -244.0,
    "GENERATE_MIN_X": -293.0,
    "GENERATE_MAX_Z": 65,
    "GENERATE_MIN_Z": 24,
    "GENERATE_Y": 0.5,

    "MAX_ENEMY_COUNT": 10000,
    "RANDOM_GENERATED_ENEMY_COUNT": [4, 7],

    "MAX_GENERABLE_ITEM": 10,

    "ENMEY_BULLET_DAMAGE": 10,
    "ENMEY_ATTACK_DAMAGE": 15,

    "PLAYER_NORMAL_SHOOT_DAMAGE": 40,
    "PLAYER_SKILL_SHOOT_DAMAGE": 30,
    "PLAYER_EXPLODE_DAMAGE": 70,

    "PLAYER_SKILL_RADIUS": 5.0,

    "PLAYER_INIT_HP": 1000,
    "PLAYER_INIT_BULLETS": 30,
    "PLAYER_INIT_MAXBULLETS": 900,

    "PLAYER_REBORN_HP": 400,
    "PLAYER_REBORN_BULLETS": 30,
    "PLAYRE_REBORN_MAXBULLETS": 300,

    "SWIM_DEBUFF_ID": 1,
    "SWIM_DEBUFF_DURATION": 3,

    "ITEM_RECOVER_HP": 600,
    "ITEM_SUPPLY": 120,

    "ENMEY_SHOOTER_INIT_HP": 100,
    "ENMEY_ATTACKER_INIT_HP": 200,

    "TANK_INIT_POSITION": [-262.0, 0.05, 42.0],

    "STRONG_POINT_POSITION": [-270.0, 2.5, 60.0],
    "STRONG_POINT_INIT_HP": 1000,

    "ENMEY_GOLD": 100,
    "SLOW_TRAP_PRICE": 200,
    "DAMAGE_TRAP_PRICE": 200,

    "TANK_INIT_HP": 1000,

    "GRENADE_PRICE": 250
}
